---
kind: Template
apiVersion: v1
metadata:
  name: gluster-s3-gateway
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: gluster-s3-gateway
      annotations:
        description: |
          Swift gateway for CNS emulating S3 API with support for
          Signature Version 4
    spec:
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: "${CONTEXT_DIR}"
      triggers:
        - type: ImageChange
        - type: ConfigChange
      strategy:
        type: Docker
        dockerStrategy:
          from":
            kind: ImageStreamTag
            name: registry.access.redhat.com/rhel7:latest
      output:
        to:
          kind: ImageStreamTag
          name: gluster-s3-gateway:latest

  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: gluster-s3-gateway
    status:
      dockerImageRepository: ""

  - apiVersion: v1
    kind: Service
    metadata:
      name: gluster-s3-gateway
      labels:
        app: swift-proxy
    spec:
      ports:
        - port: 8080
          name: swift-proxy
      clusterIP: None
      selector:
        app: swift-proxy

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: gluster-s3-gateway
    spec:
      serviceName: swift-proxy
      replicas: 1
      selector:
        app: swift-proxy
      template:
        metadata:
          labels:
            app: swift-proxy
          name: "swift-proxy"
        spec:
          containers:
            - name: gluster-s3-gateway
              image: " "
              ports:
                - containerPort: 8080
                  name: swift-proxy
              volumeMounts:
                - name: s3buckets
                  mountPath: /mnt/gluster-object
          volumes:
            - name: s3buckets
              persistentVolumeClaim:
                claimName: "gluster-s3-gateway-buckets"
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - gluster-s3-gateway
            from:
              kind: ImageStreamTag
              name: gluster-s3-gateway:latest
        - type: ConfigChange
      strategy:
        type: Rolling

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: gluster-s3-gateway-buckets
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "${BUCKETS_CAPACITY}"

parameters:
  - name: SOURCE_REPOSITORY_URL
    displayName: Source Repository URL
    description: The URL of the repository with your application source code
    value: https://github.com/miminar/gluster-s3-gateway.git
    required: true
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Repository Reference
    value: master
    required: true
  - name: BUCKETS_CAPACITY
    displayName: Buckets Storage Size
    description: Size of persistent volumes allocated for all buckets
    value: 30Gi
    required: true
  - name: CONTEXT_DIR
    displayName: Context Directory
    description: |
      Context directory inside of SOURCE_REPOSITORY_URL
      needed to build the image
    value: osapp
    required: true
  - name: INITIAL_BUCKET
    displayName: Initial bucket name
    description: |
      Name of the initial bucket. If unset, no bucket will be created.
message: "TODO: lorem ipsum"
